# game constants
SCREEN_WIDTH, SCREEN_HEIGHT = 1080, 720
FPS = 60
PLAYER_LIVES = 3
POINTS_PER_HIT = 10

# ball constants
BALL_SPEED_X = 3
BALL_SPEED_Y = -3
BALL_START_X = 540
BALL_START_Y = 670
SPEED_BOOSTS_NUMBER = 0.5

# paddle constants
PADDLE_SPEED = 4
PADDLE_STARTING_X = 500
PADDLE_STARTING_Y = 680
